# Generated by Cascade assistant to add UserLLMPreference model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deepseek_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLLMPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(max_length=64)),
                ("model", models.CharField(blank=True, default="", max_length=256)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_pref",
                        to="deepseek_api.apikey",
                    ),
                ),
            ],
        ),
    ]
