# Generated by Django 5.2.7 on 2025-10-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepseek_api', '0004_conversationsession_swap_username_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLLMAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_index=True, max_length=100)),
                ('base_url', models.CharField(max_length=512)),
                ('model_name', models.CharField(max_length=128)),
                ('api_key', models.CharField(max_length=256)),
                ('alias', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'model_name'], name='deepseek_ap_user_efd2c9_idx')],
                'unique_together': {('user', 'model_name')},
            },
        ),
    ]
