# Generated by Django 5.2.7 on 2025-11-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepseek_api', '0005_externalllmapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('user', models.CharField(db_index=True, max_length=100)),
                ('user_input', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'deepseek_api_history',
                'indexes': [models.Index(fields=['session_id', 'user', 'created_at'], name='deepseek_ap_session_102b96_idx')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('user', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deepseek_api_session',
                'indexes': [models.Index(fields=['user', 'updated_at'], name='deepseek_ap_user_8f95e4_idx')],
                'unique_together': {('session_id', 'user')},
            },
        ),
    ]
