# Generated by Django 5.2.7 on 2026-08-31 07:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deepseek_api", "0008_session_user_and_history_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="revoked_at",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "family_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("issued_at", models.IntegerField()),
                ("expires_at", models.IntegerField()),
                ("used_at", models.IntegerField(blank=True, null=True)),
                ("revoked_at", models.IntegerField(blank=True, null=True)),
                (
                    "replaced_by_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to="deepseek_api.apikey",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["family_id", "revoked_at"],
                        name="deepseek_ap_family__2aa3e4_idx",
                    ),
                    models.Index(
                        fields=["api_key", "expires_at"],
                        name="deepseek_ap_api_key_595e42_idx",
                    ),
                ],
            },
        ),
    ]
